# Generated by Django 5.0.2 on 2024-03-18 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Deck Name')),
                ('description', models.TextField(verbose_name='Deck Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='FlashCard Question')),
                ('answer', models.TextField(verbose_name='FlashCard Answer')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.deck')),
            ],
            options={
                'verbose_name': 'FlashCard',
                'verbose_name_plural': 'FlashCards',
            },
        ),
    ]
